# Numpy

In [1]:
import numpy as np

np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
np.array([[1,2,3],
          [4,5,6],  
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.array([[[0,1,2,3],
           [4,5,6,7],  
           [8,9,10,11]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0.1, 1.1, 0.1)   # A부터 B까지 C씩 증가

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
# 수의 범위를 균일하게 나누어 줌
# A부터 B까지 C개의 구간으로 분리
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [13]:
# 기타 함수를 이용한 배열 생성
print(np.ones((2,2)))
print(np.zeros((2,2)))
print(np.full((2,2), -1))
print(np.eye(2))

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[-1 -1]
 [-1 -1]]
[[1. 0.]
 [0. 1.]]


In [18]:
arr3 = np.array(
    [[
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]]
)
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [19]:
array = np.array([[1,2],[3,4]])

print('array의 차원 : ', array.ndim)
print('array의 각 차원별 크기 : ', array.shape)
print('array의 요소의 총 개수 : ', array.size)
print('array의 데이터 유형 : ', array.dtype)

array의 차원 :  2
array의 각 차원별 크기 :  (2, 2)
array의 요소의 총 개수 :  4
array의 데이터 유형 :  int32


In [20]:
print('array의 전치 (전) : ')
print(array)

print('array의 전치 (후) : ')
print(array.T)

array의 전치 (전) : 
[[1 2]
 [3 4]]
array의 전치 (후) : 
[[1 3]
 [2 4]]


* ★Numpy 배열 형태 변경 : reshape 함수 이용

In [25]:
array = np.arange(16)
print(array)
# 각 차원의 ndarray의 크기를 튜플형태로 나타냄
print(array.shape)

print(array.reshape(4,4))
print(array.reshape(4,4).shape)

print(array.reshape(-1,8))
print(array.reshape(-1,8).shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
(2, 8)


### 아파트 실거래 데이터 읽기

In [33]:

import pandas as pd

apt_price = pd.read_csv(
    './apart_price.csv', 
    encoding = 'cp949', 
    skiprows = 15,
    thousands = ','
)
apt_price

시군구       번지     본번    부번             단지명  전용면적(㎡)    계약년월  \
0      서울특별시 강남구 개포동    658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202109   
1      서울특별시 강남구 개포동    658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202112   
2      서울특별시 강남구 개포동    658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202204   
3      서울특별시 강남구 개포동    658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202204   
4      서울특별시 강남구 개포동    658-1  658.0   1.0  개포6차우성아파트1동~8동    79.97  202205   
...              ...      ...    ...   ...             ...      ...     ...   
16942  서울특별시 중랑구 중화동      450  450.0   0.0  한신아파트(103~109)    59.76  202207   
16943  서울특별시 중랑구 중화동      450  450.0   0.0  한신아파트(103~109)    84.03  202207   
16944  서울특별시 중랑구 중화동   274-51  274.0  51.0         한영(101)    84.69  202111   
16945  서울특별시 중랑구 중화동   274-51  274.0  51.0         한영(101)    84.69  202204   
16946  서울특별시 중랑구 중화동  11월 07일   11.0   7.0     현대휴앤미(102동)    76.43  202204   

       계약일  거래금액(만원)   층    건축년도          도로명  해제사유발생일  거래유형          중개사소재지  
0        2    220000   2  1987.0        언주로 3      NaN     -               -  
1        4    215000   3  1987.0        언주로 3      NaN  중개거래          서울 강남구  
2       12    220000   4  1987.0        언주로 3      NaN  중개거래          서울 강남구  
3       21    220000   2  1987.0        언주로 3      NaN  중개거래          서울 강남구  
4       27    216000   2  1987.0        언주로 3      NaN  중개거래          서울 강남구  
...    ...       ...  ..     ...          ...      ...   ...             ...  
16942   20     74000   3  1997.0      동일로 752      NaN  중개거래          서울 중랑구  
16943   27     91500  12  1997.0      동일로 752      NaN  중개거래          서울 중랑구  
16944    4     50000   2  2003.0   동일로144길 74      NaN  중개거래  서울 송파구, 서울 중랑구  
16945    9     49900   7  2003.0   동일로144길 74      NaN  중개거래          서울 중랑구  
16946   23     53000   6  2007.0  봉화산로27가길 19      NaN  중개거래          서울 중랑구  

[16947 rows x 15 columns]

In [29]:
apt_price.shape, apt_price.size

((16947, 15), 254205)

In [31]:
평 = apt_price['전용면적(㎡)'] / 3.03
평

0        26.392739
1        26.392739
2        26.392739
3        26.392739
4        26.392739
           ...    
16942    19.722772
16943    27.732673
16944    27.950495
16945    27.950495
16946    25.224422
Name: 전용면적(㎡), Length: 16947, dtype: float64

In [34]:
apt_price['거래금액(만원)'] / 평

0        8335.625860
1        8146.179817
2        8335.625860
3        8335.625860
4        8184.069026
            ...     
16942    3752.008032
16943    3299.357372
16944    1788.877081
16945    1785.299327
16946    2101.138296
Length: 16947, dtype: float64

In [56]:
apt_price[apt_price['층'] == 3]

시군구       번지      본번   부번             단지명  전용면적(㎡)    계약년월  \
1      서울특별시 강남구 개포동    658-1   658.0  1.0  개포6차우성아파트1동~8동  79.9700  202112   
10     서울특별시 강남구 개포동     1282  1282.0  0.0       개포래미안포레스트  84.8600  202109   
35     서울특별시 강남구 개포동      138   138.0  0.0        디에이치아너힐즈  76.1709  202110   
43     서울특별시 강남구 개포동      138   138.0  0.0        디에이치아너힐즈  59.7479  202205   
79     서울특별시 강남구 개포동    166-4   166.0  4.0            에버그린  84.8900  202110   
...              ...      ...     ...  ...             ...      ...     ...   
16867  서울특별시 중랑구 신내동      650   650.0  0.0           신내6대주  59.7600  202206   
16872  서울특별시 중랑구 신내동      657   657.0  0.0           신내9진흥  33.1800  202110   
16892  서울특별시 중랑구 신내동      479   479.0  0.0           중앙하이츠  84.9700  202110   
16935  서울특별시 중랑구 중화동  03월 19일    19.0  3.0         한솔e(B동)  82.6500  202112   
16942  서울특별시 중랑구 중화동      450   450.0  0.0  한신아파트(103~109)  59.7600  202207   

       계약일  거래금액(만원)  층    건축년도            도로명  해제사유발생일  거래유형          중개사소재지  
1        4    215000  3  1987.0          언주로 3      NaN  중개거래          서울 강남구  
10      28    272000  3  2020.0        개포로 264      NaN     -               -  
35      13    299500  3  2019.0         삼성로 11      NaN     -               -  
43      14    227000  3  2019.0         삼성로 11      NaN  중개거래          서울 강남구  
79      15    120000  3  2003.0        선릉로8길 5      NaN     -               -  
...    ...       ... ..     ...            ...      ...   ...             ...  
16867    9     67800  3  1996.0      신내로19길 42      NaN  중개거래  서울 광진구, 서울 중랑구  
16872    7     46000  3  1996.0        신내로 127      NaN     -               -  
16892    4     74500  3  1996.0  봉화산로56길 145-1      NaN     -               -  
16935   13     32500  3  2004.0     봉화산로27길 30      NaN   직거래               -  
16942   20     74000  3  1997.0        동일로 752      NaN  중개거래          서울 중랑구  

[1153 rows x 15 columns]

In [62]:
# 서울특별시 강동구 암사동 거래정보만 추출

bidx = apt_price['시군구'] == '서울특별시 강동구 암사동'

print(sum(bidx))      # True = 1, False = 0  : 조건에 맞는 정보만 count
apt_price[bidx]       # True에 위치하는 행들만 추출

78


시군구     번지     본번   부번           단지명   전용면적(㎡)    계약년월  계약일  \
1625  서울특별시 강동구 암사동  466-3  466.0  3.0         내일쎄닛빌  111.4000  202205   11   
1626  서울특별시 강동구 암사동    461  461.0  0.0            대원   59.9000  202201   17   
1627  서울특별시 강동구 암사동  501-4  501.0  4.0         동양넥스빌   84.6800  202205   10   
1628  서울특별시 강동구 암사동  414-2  414.0  2.0       롯데캐슬퍼스트   59.9900  202109    8   
1629  서울특별시 강동구 암사동  414-2  414.0  2.0       롯데캐슬퍼스트   59.9900  202109   11   
...             ...    ...    ...  ...           ...       ...     ...  ...   
1698  서울특별시 강동구 암사동    400  400.0  0.0         현대홈타운   84.9800  202204   20   
1699  서울특별시 강동구 암사동    400  400.0  0.0         현대홈타운  114.0700  202205   30   
1700  서울특별시 강동구 암사동    675  675.0  0.0  힐스테이트 강동 리버뷰   84.9979  202203   29   
1701  서울특별시 강동구 암사동    675  675.0  0.0  힐스테이트 강동 리버뷰   84.9921  202204    1   
1702  서울특별시 강동구 암사동    675  675.0  0.0  힐스테이트 강동 리버뷰   84.9628  202205    6   

      거래금액(만원)   층    건축년도         도로명  해제사유발생일  거래유형          중개사소재지  
1625     72000   9  2007.0  고덕로20나길 49      NaN   직거래               -  
1626     72500  12  1998.0      고덕로 52      NaN  중개거래  서울 강남구, 서울 강동구  
1627     80000  10  1999.0      상암로 41      NaN  중개거래          서울 강동구  
1628    129700  18  2008.0     고덕로 131      NaN     -               -  
1629    125500   3  2008.0     고덕로 131      NaN     -               -  
...        ...  ..     ...         ...      ...   ...             ...  
1698    137500  18  2004.0   고덕로27길 36      NaN  중개거래          서울 강동구  
1699    155000  11  2004.0   고덕로27길 36      NaN  중개거래          서울 강동구  
1700    130000   4  2019.0  올림픽로91길 30      NaN  중개거래          서울 강동구  
1701    164000  23  2019.0  올림픽로91길 30      NaN  중개거래          서울 강동구  
1702    152000   7  2019.0  올림픽로91길 30      NaN  중개거래        경기 성남분당구  

[78 rows x 15 columns]

### Numpy Op

In [41]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

# 내적연산
print(x@y)
print(np.dot(x,y))

# 제곱근
print(np.sqrt(x))
# 행렬 곱
print(np.matmul(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[19 22]
 [43 50]]


## Numpy Indexing


* 조건인덱싱: 1차원 True, False 배열을 2차원 배열의 조건으로 제공하면 True에 해당하는 행들이 반환

In [36]:
# 현재 메모리에 존재하는 변수 이름과 그 값을 출력
# %는 주피터 명령어 not python
%whos

Variable    Type         Data/Info
----------------------------------
apt_price   DataFrame                     시군구     <...>[16947 rows x 15 columns]
arr3        ndarray      3x2x3: 18 elems, type `int32`, 72 bytes
array       ndarray      16: 16 elems, type `int32`, 64 bytes
np          module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
pd          module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
평           Series       0        26.392739\n1    <...>th: 16947, dtype: float64


In [39]:
arr5 = np.arange(9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
print(arr5[1][1])
print(arr5[1,1])

4
4


In [46]:
arr5[-1,-1]

8

In [47]:
# ★ 중요하다네요

bidx = arr5 % 2 == 0
bidx

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [51]:
print(arr5[bidx])    # True에 위치하는 값을 추출, 1차원 반환

print(arr5[arr5 % 2 == 0])    # 조건 + 인덱싱

[0 2 4 6 8]
[0 2 4 6 8]


In [63]:
# ★ row와 col 행렬의 길이가 동일해야함
row = [0,1]   # 행만 모아서 넘겨줌
col = [2,1]   # 열만 모아서 넘겨줌

print(arr5)
print(arr5[row,col])
print(arr5[[0,1],[2,1]])     # arr5[0,2], arr5[1,1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2 4]
[2 4]


In [65]:
print(arr5)
print(arr5[0,:])        # [0, 1, 2]     : 1차원
print(arr5[:,1])        # [1, 4, 7]     : 1차원 
print(arr5[:2,1:])      # [[1,2],[4,5]] : 2차원
print(arr5[-1:,1:3])    # [[7,8]]       : 2차원

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[1 4 7]
[[1 2]
 [4 5]]
[[7 8]]


In [72]:
a = arr5[:,1].copy()      # 복사본
b = arr5[:,1]             # 값을 그대로 받아오면 원본행렬에도 영향

a[0] = 10
print(a)
print(arr5)

b[0] = 10
print(b)
print(arr5)

[10  4  7]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[10  4  7]
[[ 0 10  2]
 [ 3  4  5]
 [ 6  7  8]]


## Numpy Func

* 팬시인덱싱 ? 행 따로, 열 따로

In [80]:
print(np.where(arr5 % 2 == 0))    # 행, 열 좌표를 따로 출력
np.where(arr5 % 2 == 0, '짝수', '홀수')

(array([0, 0, 1, 2, 2], dtype=int64), array([0, 2, 1, 0, 2], dtype=int64))


array([['짝수', '홀수', '짝수'],
       ['홀수', '짝수', '홀수'],
       ['짝수', '홀수', '짝수']], dtype='<U2')

In [86]:
# 조건에 맞는 항목은 "짝수", 아니면 원래 값 유지

np.where(arr5 % 2 == 0, '짝수', arr5)

array([['짝수', '1', '짝수'],
       ['3', '짝수', '5'],
       ['짝수', '7', '짝수']], dtype='<U11')

In [87]:
print(arr5)
arr5.sum()

[[0 1 2]
 [3 4 5]
 [6 7 8]]


36

In [89]:
print(arr5.sum(axis=0))    # axis = 0 은 '열'별 통계 
print(arr5.sum(axis=1))    # axis = 1 은 '행'별 통계

[ 9 12 15]
[ 3 12 21]
